---
title: "Data tidying"
author: "Jen Marsh"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(tidyr)
```

Read in Data from [KNB DATA](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1)

```{r import data}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```
select column, move from wide to long and rename columns
```{r selecting_columns}
catch_df <- catch_df %>%
  select(-All, -notesRegCode) %>% 
  gather(key = species, value = catch, -Region, -Year) %>% 
  rename(catch_thousands = catch, Species=species)
head(catch_df)
```
Correct typo and change units

```{r}
catch_df <- catch_df %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands)) %>%
  mutate(catch_thousands = as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands*1000)
head(catch_df, 30)
  
```
